name: Build and Upload Python Package

on: 
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
 
    - name: Build and publish
      env:
        PYPI_SCM_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_SCM_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --build -u $PYPI_SCM_USERNAME -p $PYPI_SCM_PASSWORD
