name: Upload Python Package

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Check formatting
      run: |
        poetry run black --check wknml tests examples
    - name: Test
      run: |
        mkdir -p testoutput
        poetry run pytest tests
    - name: Build and publish
      if: startsWith(github.event.ref, 'refs/tags')
      env:
        PYPI_SCM_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_SCM_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --build -u $PYPI_SCM_USERNAME -p $PYPI_SCM_PASSWORD
