name: Test Python Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64' # (x64 or x86)

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Check formatting
      run: |
        poetry run black --check wknml tests examples

    - name: Unit Tests
      run: |
        mkdir -p testoutput
        poetry run pytest tests

    - name: Check Documentation for updates
      run: |
        poetry run pydoc-markdown -m wknml --render-toc > docs/ci_test.md
        diff docs/ci_test.md docs/wknml.md
        rm docs/ci_test.md
